docs/prerequisites.md
thundernetes prerequisites document.
=> Created prerequisites.md

docs/troubleshooting/Cluster/README.md, docs/troubleshooting/Deployment/README.md, docs/troubleshooting/GameServers/HowCanIFindThePublicIPAddress.md, docs/troubleshooting/GameServers/HowCanIRunMyGameServerPodInANonDefaultNamespace.md, docs/troubleshooting/GameServers/HowToScheduleGameServerNodes.md, docs/troubleshooting/GameServers/MyGameServerIsStuck.md, docs/troubleshooting/GameServers/README.md, docs/troubleshooting/Kubernetes/README.md, docs/troubleshooting/Metrics/README.md, docs/troubleshooting/README.md, docs/troubleshooting/Security/README.md
Created troubleshooting guide.
=> Created troubleshooting guide and categories

README.md
Creating a release shield for thundernetes releases.
=> adding release shield

.github/workflows/codeql-analysis.yml
An attempt to fix CodeQL step, since the GitHub action is stuck https://github.com/PlayFab/thundernetes/actions/runs/1473889145 because of the sidecar wanting env variables for initialization.
=> attempt to fix CodeQL

.github/workflows/main.yml, e2e/cmd/main.go, e2e/cmd/utilities.go, operator/Makefile, operator/api/v1alpha1/gameserver_types.go, operator/config/crd/bases/mps.playfab.com_gameservers.yaml, operator/config/manager/kustomization.yaml, operator/controllers/gameserver_controller_test.go, operator/controllers/gameserverbuild_controller.go, operator/controllers/gameserverbuild_controller_test.go, samples/netcore/Startup.cs, sidecar-go/sidecarmanager.go
Fixes #67 
A first attempt in updating the GameServer CR status.state when the game server process state is "Initializing". Draft since we need tests etc.
=> Update GameServer.Status.State when initializing

CONTRIBUTING.md, README.md, docs/contributing.md
Created initial Contribution guide that we can build on as the project grows
Signed-off-by: Ken Haines <1144092+khaines@users.noreply.github.com>
=> Initial Contributors documentation

operator/controllers/gameserverbuild_controller.go
during the attempt to fix the flaky unit test, we noticed a bug on the counters on GameServerBuild controller. This PR fixes it.
=> fixing bug on counters

docs/troubleshooting/README.md
Updated troubleshooting broken link for Game Server.
=> Updated README.md

docs/yourgameserver.md
Fixes #87 
A small addition to the documentation, provides information about GameServerBuild image upgrades.
=> adding information about game server upgrades

.versions, CHANGELOG.md, README.md, docs/development.md, installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, pkg/operator/config/manager/kustomization.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-secondnodepool.yaml, samples/netcore/sample.yaml
This PR configures the repo for 0.2.0 release of thundernetes!
=> configuring repo for 0.2

.github/workflows/main.yml, docs/FAQ.md, docs/yourgameserver.md, pkg/operator/config/samples/netcore.yaml, samples/netcore/sample-hostnetwork.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-secondnodepool.yaml, samples/netcore/sample.yaml, samples/openarena/sample.yaml
Fixing the regression introduced with the change in the container image name changes.
=> fixing sample names

pkg/operator/api/v1alpha1/gameserverbuild_types.go, pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml, pkg/operator/config/manager/kustomization.yaml, pkg/operator/controllers/gameserver_controller.go, pkg/operator/controllers/gameserverbuild_controller.go, pkg/operator/http/allocate.go
Fixes #142 
This PR switches from .Update to .Patch for controller operations.
=> replacing .Update with .Patch

cmd/nodeagent/nodeagentmanager.go
This PR removes hardcoded JSON from the NodeManager. Draft till we run more tests.
=> removing hardcoded json

cmd/nodeagent/nodeagentmanager.go
Fixes #75 
This PR introduces ConnectedPlayers count as a prometheus metric in the NodeAgent.
=> adding connected players prometheus gauge

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, samples/netcore/sample-hostnetwork.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-requestslimits.yaml, samples/netcore/sample-secondnodepool.yaml, samples/netcore/sample.yaml
Tested release 0.3, changing the samples to point to the new release! Happy 0.3!
=> adding 0.3 to the samples

README.md
Closes #80 
Adding YouTube video from GDC 2022!
=> adding YouTube video

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, samples/netcore/sample-hostnetwork.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-requestslimits.yaml, samples/netcore/sample-secondnodepool.yaml, samples/netcore/sample.yaml, samples/openarena/sample.yaml
I believe I updated all relevant yaml files, if you know another please let me know.
=> updated version to 0.3.1 in relevant yaml files

pkg/operator/PROJECT, pkg/operator/api/v1alpha1/gameserver_webhook.go, pkg/operator/api/v1alpha1/gameserver_webhook_test.go, pkg/operator/api/v1alpha1/gameserverbuild_webhook_test.go, pkg/operator/api/v1alpha1/webhook_suite_test.go, pkg/operator/config/webhook/manifests.yaml, pkg/operator/main.go
Fixes #223
Added webhooks for GameServers and tests.
=> Validate GameServer objects

cmd/nodeagent/main.go, cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go, cmd/nodeagent/types.go, cmd/nodeagent/utilities.go
=> Mark GameServers as unhealthy when no heartbeats are received

cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go, cmd/nodeagent/utilities.go
=> Fix nodeagent unit tests

cmd/gameserverapi/main.go
Added a cors policy to the game server api so it accepts requests from other origins.
=> Added middleware function with cors policy

pkg/operator/controllers/allocation_api_server.go
Added cors policy for allocate api.
=> Cors allocate

Makefile
Fixes #243 
This PR upgrades kind to 0.13.
=> Upgrading kind to 0.13

.versions
Updating version for 0.4.1 release
=> version 0.4.1

cmd/allocator/main.go, cmd/e2e/gameserverapi_test.go, cmd/gameserverapi/main.go, cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go, cmd/nodeagent/types.go, cmd/nodeagent/utilities.go, cmd/qosserver/main.go, pkg/operator/controllers/suite_test.go
Ran `go fmt ./...` and `go vet ./...`
=> Running go fmt and go vet

Makefile
This PR updates kind to 0.14 https://github.com/kubernetes-sigs/kind/releases/tag/v0.14.0
=> Update kind to 0.14

.github/workflows/main.yml, build-env/Dockerfile, cmd/initcontainer/Dockerfile.win, cmd/nodeagent/Dockerfile.win, go.mod, go.sum, pkg/operator/Makefile
=> upgrade to Go 1.18

.github/workflows/main.yml
This PR modifies our CI GitHub action to make sure contributors have run:
- go vet
- go fmt
- go mod tidy
before pushing the PR.
=> modifying CI GitHub action

cmd/e2e/scale_nodes_test.go, pkg/operator/config/manager/manager.yaml, pkg/operator/controllers/gameserver_controller.go, pkg/operator/controllers/port_registry.go, pkg/operator/controllers/port_registry_test.go
Some fixes for logging in PortRegistry.
=> logging for PortRegistry

docs/gameserverapi/apidocs.md
Added missing value so the markdown inside a detail tag is parsed, also some spacing changes.
=> Fixed markdown not being parsed in GameServer API docs

docs/quickstart/allocation-scaling.md
Updating documents for quickstart to help with the 'kind' example. Also modifying 'here' links to be more descriptive in that document.
=> Modified documents for kind quickstart

samples/grafana/dashboard.json
Part of #280
To test this, try following [this guide](https://playfab.github.io/thundernetes/howtos/monitoring.html) but import this json instead.
=> Added more graph examples to the Grafana dashboard

cmd/gameserverapi/deployment/default/deploy.yaml, cmd/latencyserver/deploy.yaml
updating images for gameserverapi/latencyserver to 0.5.0
=> updating images for gameserverapi/latencyserver

cmd/gameserverapi/deployment/default/deploy.yaml, cmd/latencyserver/deploy.yaml
Reverts PlayFab/thundernetes#334
=> Revert "updating images for gameserverapi/latencyserver"

.versions
Upgrading version for release of 0.5.0
=> Upgrade to version 0.5.0

docs/_includes/gsdkfooter.md, docs/gsdk/csharpcppjava.md, docs/gsdk/unity.md, docs/gsdk/unreal.md
=> fixing footer

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, samples/gameserverapi/gameserverapi.yaml, samples/latencyserver/latencyserver.yaml, samples/netcore/sample-hostnetwork.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-requestslimits.yaml, samples/netcore/sample-secondnodepool.yaml, samples/netcore/sample-win.yaml, samples/netcore/sample.yaml, samples/openarena/sample.yaml
Updated install files and samples to version 0.5.0
=> Installfiles 0.5.0

cmd/e2e/utilities_test.go
This PR fixes the fetching of the status message for e2e tests.
=> fixing logs for e2e tests

.github/workflows/pages-check-links.yml
Related to #340 
Should work according to this https://github.com/ruby/setup-ruby#supported-version-syntax
=> Changing version format in setup ruby action

cmd/e2e/utilities_test.go
Better logging for e2e flakey test
=> e2e logging for flakey test

pkg/operator/controllers/gameserver_controller.go
This PR removes an unnecessary log line that was merged by mistake.
=> removing a wrong log

docs/development/debugging.md
Adding instructions for kustomize in the docs.
=> adding instructions for kustomize

samples/grafana/dashboard.json
Fixes a small issue on the sample Grafana dashboards
=> fix for Grafana sample

.github/workflows/pages-check-links.yml, docs/gameserverapi/gameserverapi_swagger.md
This PR aims to fix "check broken links" GitHub Action
=> attempt to fix "check broken links" GitHub Action

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameserverdetails.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml, samples/gameserverapi/gameserverapi.yaml, samples/latencyserver/latencyserver.yaml, samples/netcore/sample-hostnetwork.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-requestslimits.yaml, samples/netcore/sample-secondnodepool.yaml, samples/netcore/sample-win.yaml, samples/netcore/sample.yaml, samples/openarena/sample.yaml, samples/server-load-simulator/simulator.yaml, samples/standby-forecaster/forecaster.yaml, tests/scalability/max/10.yaml, tests/scalability/max/50.yaml
This PR updates installfiles and samples to use the 0.6.0 version.
=> 0.6.0 installfiles and samples

docs/Gemfile.lock, docs/howtos/serviceingress.md, docs/quickstart/allocation-scaling.md, docs/quickstart/installing-thundernetes.md
This PR adds some instructions on generating a certificate for testing using cert-manager.
=> Certificate generation using cert-manager

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml
#446 introduced a regression in creating the installation files, this PR fixes it.
=> updating installfiles

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, pkg/operator/Makefile, pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameserverdetails.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml, pkg/operator/controllers/allocation_api_server_test.go, pkg/operator/controllers/gameserver_expectations_test.go, pkg/operator/controllers/test_utils_test.go
This PR fixes a regression in unit tests.
=> fixing unit tests

cmd/e2e/gameserverapi_test.go, cmd/e2e/utilities_test.go, cmd/gameserverapi/main_test.go, cmd/initcontainer/main_test.go, cmd/nodeagent/main.go, cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go, cmd/nodeagent/types.go, pkg/operator/controllers/allocation_api_server_test.go
Adding support for logging GSDK metrics to the NodeAgent
=> adding GSDK metrics
