PlayFab/thundernetes

operator/controllers/gameserverbuild_controller_test.go, sidecar-go/httphandler.go
Renaming the phrase "CRD instance" to the more accurate  and simpler "CR"
=> renaming CRD instance to CR

.github/workflows/main.yml, initcontainer/go.mod, initcontainer/go.sum, initcontainer/main.go, initcontainer/main_test.go
While [creating the Go GSDK](https://github.com/PlayFab/gsdk/pull/103) and testing with the [LocalMultiplayerAgent](https://github.com/PlayFab/MpsAgent), we found out that the GsdkConfig.GamePorts field should actually be map[string]string instead of map[string]int. We verified it by checking some MPS VMs as well. As we copied this type on the Go GSDK from the one here in the thundernetes repo, we should make that change here as well. Created #57 to create unit tests for initcontainer as well.
=> fix for GsdkConfig

sidecar-go/main.go, sidecar-go/sidecarmanager.go, sidecar-go/sidecarmanager_test.go
Fixing #37 
Small impact PR that renames the main struct of the sidecar, since it evolved more than just an http handler.
=> refactoring sidecar

e2e/cmd/main.go
#68 included a bad return that ended e2e tests prematurely. This PR removes it. Plus, switched to the original namespace for the tests.
=> removing bad return

CHANGELOG.md
Adds a simple Changelog.md to the repository for tracking additions & changes for each release.
=> Adding a CHANGELOG to track updates to the project.

initcontainer/main.go, initcontainer/main_test.go, operator/controllers/utilities.go
Fixes #53 
This PR adds the Node Internal IP to the list of environment variables obtained by the initcontainer and passed into the gsdkConfig.json file. This is used in the GetPublicIP API of the GSDK. Workarounds will be provided in the documentation for users that want to obtain the actual Public (External) IP. We also opportunistically fixed getting the actual Node name passed in "PF_VM_ID" environment variable.
#86 gets the actual Public IP but the code was deemed "too much".
=> adding node internal ip + node name

e2e/cmd/main.go
Currently, during e2e tests we are "GETting" GameServerBuilds into the same variable. This has the unfortunate consequence of some GameServerBuilds getting overwritten (e.g. the "testBuild" had an unwanted env variable). This PR resets the variable before every "GET".
=> fixing e2e tests

operator/controllers/gameserverbuild_controller_test.go
Fixes #40 
GameServerBuild controller tests are sometimes flaky. This PR increases the timeout for an assertion which gave us problems in the past, e.g. https://github.com/PlayFab/thundernetes/runs/4427358325
Added code from #102
=> increasing timeout for GameServerBuild controller test

operator/controllers/gameserver_controller.go
This PR updates the GameServerController code with .Patch instead of .Update for adding Pod SafeToEvict annotations. Draft till we make sure that this Patch code is the best.
It was discovered from here https://sdk.operatorframework.io/docs/building-operators/golang/references/client/#patch, we should make sure that there's no more performant way than using Pod.DeepCopy.
=> replacing update with patch on pod annotations

operator/http/http.go
This PR adds timeout to Allocation API service, to protect the HTTP server instance.
=> adding timeout to Allocation API service

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml
A recent PR introduced a change in the environment variable that the operator uses to look for a potential TLS secret. While e2e tests worked for newer commits, version 0.1 (the one in the current quickstart) fails to start. The PR fixes it.
=> reverting old values for the quickstart

samples/netcore/Dockerfile, samples/netcore/netcore.csproj, samples/openarena/Dockerfile, samples/openarena/openarena.csproj
Signed-off-by: Dimitrios Ilias Gkanatsios <dgkanatsios@outlook.com>
Converting netcore sample and openarena to work with .NET 6. Moreover, removing the x64 build from the `botnet publish` command. This has the effect of building for whatever architecture the container is running on, enabling the end to end tests to run on MacOS with M1 (Apple Silicon) processor.
=> .net 6 for .NET sample and open arena

docs/FAQ.md, nodeagent/utilities.go, operator/config/manager/kustomization.yaml, samples/unity/README.md, samples/unity/sample.yaml
This PR partially fixes #60.
It adds some documentation for running Unity game servers on thundernetes. Moreover, since the [Unity GSDK](https://github.com/PlayFab/gsdk/tree/master/UnityGsdk) does not send any information, we modified the NodeAgent to convert empty strings to "Healthy".
=> fixes for Unity GSDK

docs/FAQ.md
Enhancing the documentation for multiple Node Pools.
=> adding multiple node pools, fixes #74

go.mod, go.sum, pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml, pkg/operator/controllers/gameserver_controller.go, pkg/operator/controllers/gameserverbuild_controller.go
Using sync.map on the controllers, eliminating an unnecessary dependency. Moreover, publishing updated YALM OpenAPI files, as a result of #119.
=> using sync.map

cmd/e2e/utilities.go, pkg/operator/config/manager/kustomization.yaml, pkg/operator/controllers/gameserverbuild_controller.go
=> Attempt to fix the unit test bug

cmd/e2e/main.go, docs/yourgameserver.md, pkg/operator/controllers/gameserverbuild_controller_test.go, pkg/operator/controllers/utilities.go, samples/netcore/Program.cs, samples/netcore/sample-hostNetwork.yaml, samples/netcore/sample-hostnetwork.yaml, samples/netcore/sample-nodeaffinity.yaml, samples/netcore/sample-secondnodepool.yaml
Fixes #22 
This PR enables the utilization of hostNetwork mode on GameServer Pods, if selected by the user. It also
- adapts netcore sample so it loads the port via GSDKConfig (best practice on MPS as well, but old code should still work).
- adds a unit test for hostNetwork mode
- adds a relevant sample
- fixes naming on sample files for consistency
=> Support setting GameServers Pods to host network

docs/FAQ.md
Fixes #109 
This PR adds some documentation about Pod priority that may have an impact on a potential race condition between DaemonSet Pod and GameServer Pod(s) on a new cluster Node.
=> adding information about Pod Priority

docs/FAQ.md, docs/prerequisites.md
Removing because https://github.com/PlayFab/thundernetes/issues/5#issuecomment-1015892564
=> removing Virtual Kubelet from docs

pkg/operator/http/http.go, pkg/operator/main.go
This PR renames ApiServer struct to AllocationApiServer, to make the distinction between it and the GameServer API service more clear.
=> rename to allocationapiserver

cmd/e2e/utilities.go
A recent PR (#143) seems to have made the controller react different to multiple crashes occurring at the same time introducing a transient issue https://github.com/PlayFab/thundernetes/runs/4903482916?check_suite_focus=true
This PR makes the test suite more flexible by allowing more than expected crashes to be valid.
=> fix crashes test

pkg/operator/controllers/gameserverbuild_controller.go
When deleting a GameServer in cases of reduced StandingBy, we checked the cache for Initializing or StandingBy servers. However, there is a chance that the cache might have not been updated so we could delete GameServers that have been transitioned to Active. This PR updates the DELETE API Call to check for the ResourceVersion of the GameServer to be deleted. The ResourceVersion changes if the object is updated (either in .Spec or in .Status) so this change will return 409 (Conflict) if this is the case.
=> adding ResourceVersion in deletes

pkg/operator/http/allocate.go
Current allocation logic with PATCH the .status.state of a GameServer Custom Resource with the new "Active" state. However, there are cases in which this might create issues since PATCH does not check the current state of the object. For example, the object might have been deleted or crashed and the cache might have not been updated. This will lead to the allocation API service returning an invalid active game server to the caller. To prevent this, we are switching the Patch with Update which will fail if the object's state has changed. 
For the time being, this will require the customer to implement a retry logic till we can implement some retry logic ourselves, maybe as part of #7.
=> replacing patch with update during allocation

docs/gameserverbuild.md, pkg/operator/controllers/gameserverbuild_controller.go
Fixes #155 
Currently, once the GameServerBuild becomes unhealthy, no other operation (controller reconciliation) will take place on the GameServerBuild. This can be a blocker on some scenarios where we want this to continue. We need to think of a better overall solution, but for the time being this PR allows the user to increase the value of the GameServerBuild.Spec.CrashesToMarkUnhealthy so the controller will continue to perform reconciliations on it.
=> unblocking unhealthy GameServerBuild

docs/README.md, docs/usingwrapper.md, samples/fileshare/sample.yaml
Fixes #148 
adds information about how to quickly start with your game server on thundernetes without integrating with GSDK by using a custom wrapper from https://github.com/PlayFab/MpsSamples repository.
Also adding a table of contents for our documentation.
=> adding wrapper sample and docs

Makefile, cmd/e2e/gameserverapi_test.go, cmd/e2e/main.go, cmd/e2e/suite_test.go, cmd/e2e/tools.go, cmd/gameserverapi/deploy.yaml, cmd/gameserverapi/main.go, cmd/gameserverapi/main_test.go, cmd/nodeagent/nodeagentmanager_test.go, e2e/kind-config.yaml, e2e/run.sh, go.mod, go.sum, pkg/operator/config/manager/kustomization.yaml, pkg/operator/controllers/gameserver_controller_test.go, pkg/operator/controllers/gameserverbuild_controller.go, pkg/operator/controllers/gameserverbuild_controller_test.go, pkg/operator/controllers/port_registry_test.go, pkg/operator/controllers/suite_test.go, pkg/operator/controllers/utilities_test.go, pkg/operator/http/allocate_test.go, pkg/operator/http/types_test.go
Fixes #123 
- Adds end to end tests for GameServer API
- Refactors the URLs for GameServer API to /api/v1/... (breaking change)
- Adds gingo functionality in preparation for #1
=> adding tests && refactoring gameserver api

.github/workflows/codeql-analysis.yml, README.md, cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/utilities.go
Fixes #85 
This PR tried to introduce CodeQL again, since we removed the sidecar that was causing issues.
=> Try CodeQL again

.github/workflows/main.yml, docs/quickstart.md, docs/yourgameserver.md, samples/openarena/README.md
Fixes #159
This PR replaces "master" with "main" in the workflows and documentation. We'd still need to change the name of the branch using the instructions here https://github.com/github/renaming
=> renaming master to main

Makefile, go.mod, go.sum, pkg/operator/config/manager/kustomization.yaml, pkg/operator/controllers/gameserver_controller.go, pkg/operator/controllers/gameserverbuild_controller.go, pkg/operator/http/allocate.go
Minor refactorings on the project.
Details:
1. Removes the sorting for the GameServers in the GameServerBuild controller. The sorting was meant to make for faster deletion, since Initializing and StandingBy servers would be in the first places of the array. However, Initializing could convert to StandingBy which would have changed their ResourceVersion, so there would be conflicts in deleting them. So we decided to remove the sorting and potentially get some CPU cycles back.
2. Simplifies the if checks by combining the non active game servers count into a single variable
3. creates a function for game server deletion, that checks for the resource version before deletion. If the CR has been updated, deletion will return a conflict
4. Updates the addSafeToEvictAnnotation method to add the …
=> Various refactorings

docs/_config.yml, docs/usingwrapper.md
This PR fixes the "edit on GitHub" button on docs.
=> fixing the edit on GitHub docs button

docs/architecture.md, docs/gameserverbuild.md, docs/gameserverlifecycle.md, docs/howtos/nodepools.md, docs/howtos/runlocalmultiplayeragent.md, docs/quickstart.md, docs/usingwrapper.md, docs/yourgameserver.md
This PR does some minor corrections to the documentation, mainly adding the `> _**NOTE**_:` markdown element which works better on Jekyll theme.
=> minor corrections to the documentation

samples/openarena/Dockerfile, samples/openarena/sample.yaml
- Added missing tag in the openarena sample Dockerfile.
- Fixed image version in the openarena sample yaml file.
=> Added missing tag in openarena Dockerfile.

cmd/e2e/allocation_test.go, cmd/e2e/suite_test.go, e2e/run.sh, pkg/operator/config/manager/kustomization.yaml, pkg/operator/http/http.go, pkg/operator/http/types.go
Added a test that checks that you can't allocate gameservers when using a wrong TLS certificates.
=> Test allocate wrong tls credentials

.github/workflows/main.yml
This PR updates the CI test to use 1.17.x of Go instead of 1.17.5
=> specifying latest 1.17 go version for tests

docs/architecture.md
The architecture image looks quite small when it appears on the site. This PR makes it linkable to the full image.
=> making the architecture image link

cmd/initcontainer/main.go, pkg/operator/controllers/utilities.go
Fixes #197 
This PR does two things
- it adds a method on initContainer which creates a log folder for the GSDK to access, if needed
- it adds an environment variable on game server with the location of this log folder. This is useful for Unreal game server builds, since on MPS they have to change the log folder permissions, as per https://github.com/PlayFab/gsdk/blob/main/UnrealPlugin/ThirdPersonMPCloudDeploy.md#startupsh-bash-script
=> creating log folders on InitContainer

pkg/operator/Makefile, pkg/operator/config/default/manager_auth_proxy_patch.yaml
=> Updating project for kubebuilder 3.4

.github/workflows/main.yml, pkg/operator/Makefile
Fixes #134 
This PR adds an extra step into our CI pipeline where it will generate the install files (`make create-install-files`) and then check if the repo has been dirty. This is for cases where we upgrade dependent libraries (e.g. controller-runtime) and this will change the YAML generated files that our operator is based on. In these cases, we should create a new Thundernetes version.
=> checking if make create-install-files makes the repo dirty

pkg/operator/controllers/gameserverbuild_controller.go
GameServerBuild controller incorrectly checkes for DeletionTimestamp to remove a GameServerBuild entry from an internal cache. There is no finalizer on the GameServerBuild CR, so the removal never occurs. This PR moves the code to the first parts of the Reconcile method where the code tries to fetch the GameServerBuild CR instance.
=> fix deleting from crashesPerBuild map

cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go, cmd/nodeagent/utilities.go
We noticed that there were a lot of errors during NodeAgent unit tests, because "Build ID is missing". This PR fixes the test by adding Build Name (which was the actual attribute that was missing) in the Unit test objects.
=> fixing NodeAgent tests

pkg/operator/api/v1alpha1/gameserverbuild_webhook_test.go
Occasionally, we've seen a webhook test fails since the GameServerBuilds are created fast and so a subsequent call with the same BuildID will bypass the cache. For example https://github.com/PlayFab/thundernetes/runs/6874395350?check_suite_focus=true
This PR adds code to check that the new GameServerBuild is part of the cache before proceeding.
=> fixing webhook test

cmd/e2e/build_crashing_test.go, cmd/e2e/build_host_network_test.go, cmd/e2e/build_sleep_before_readyforplayers_test.go, cmd/e2e/build_unhealthy_gameservers_test.go, cmd/e2e/build_without_readyforplayers_test.go, cmd/e2e/utilities_test.go, cmd/gameserverapi/main.go, installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, pkg/operator/api/v1alpha1/gameserver_types.go, pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml, pkg/operator/controllers/gameserver_controller.go, pkg/operator/controllers/gameserverbuild_controller.go, pkg/operator/controllers/metrics.go, pkg/operator/controllers/test_utils_test.go
Fixes #56 
This PR modifies the GameServerBuild controller to delete a GameServer when its status becomes Unhealthy.
As a side effect, we expect it to fix #256 and #257 since Unhealthy GameServers won't exist in the cluster any more so:
i) they won't be taken into account when scaling
ii) NodeAgent will get a notification about their deletion so it will not repeatedly try to mark them as Unhealthy
The change in the YAML files is probably due to the new C-R version that was merged in a different PR.
=> Deleting Unhealthy game servers

cmd/nodeagent/nodeagentmanager_test.go, pkg/operator/api/v1alpha1/gameserverbuild_webhook.go, pkg/operator/api/v1alpha1/gameserverbuild_webhook_test.go
This PR marks the unique BuildID test as Flakey since sometimes the cache is not updated for two different GameServerBuild creation calls. It also adds a comment so we can close #238
=> making unique BuildID webhook test flakey

installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, pkg/operator/Makefile, pkg/operator/api/v1alpha1/gameserver_types.go, pkg/operator/api/v1alpha1/gameserver_webhook_test.go, pkg/operator/api/v1alpha1/gameserverbuild_types.go, pkg/operator/api/v1alpha1/gameserverbuild_webhook_test.go, pkg/operator/config/crd/bases/mps.playfab.com_gameserverbuilds.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameserverdetails.yaml, pkg/operator/config/crd/bases/mps.playfab.com_gameservers.yaml, pkg/operator/controllers/gameserverbuild_controller_test.go, pkg/operator/controllers/suite_test.go, pkg/operator/controllers/test_utils_test.go
While working on #265, we discovered that the presence of `omitEmpty` on the CR type definition makes the field optional and the `required` annotation is ignored. This PR fixes it. Opportunistically, we update controller-tools to 0.9.0.
PR also updates current installation files. We're adding behavior that should already be there, so no new Thundernetes version is required.
For reference: https://github.com/kubernetes-sigs/controller-tools/issues/599
=> fix required fields bug

cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go
Currently, the createUpdateHandler on NodeAgent will continue execution if the GameServer is Unhealthy and gets to Active (or first gets to Active then become Unhealthy). This PR prevents the running method from executing further when the GameServer is marked us Unhealthy.
Opportunistically, makes GameServer related logging on the NodeAgent much more verbose.
=> preventing Unhealthy GameServers from creating GameServerDetail

cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go, cmd/nodeagent/types.go
Added MarkedUnhealthy field to GameServerInfo to avoid marking them more than once in the HeartbeatTimeChecker
Fixes #257
=> HeartbeatTimeChecker only marks as Unhealthy once

cmd/e2e/build_crashing_test.go, cmd/e2e/scale_nodes_test.go, e2e/run.sh, installfiles/operator.yaml, installfiles/operator_with_monitoring.yaml, installfiles/operator_with_security.yaml, installfiles/operator_with_security_and_monitoring.yaml, pkg/operator/config/e2e/kustomization.yaml, pkg/operator/config/e2e/manager_e2e.yaml, pkg/operator/config/manager/manager.yaml, pkg/operator/controllers/port_registry.go, pkg/operator/main.go
This PR
- adds a LOG_LEVEL env variable to the controller manager, with default value "info"
- configures the same value to "debug" on e2e tests
- enhances the e2e tests with a worker Node becoming unavailable (cordon and drain) and available again.
=> Add node scaling to e2e tests

cmd/nodeagent/main.go, cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go
Sometimes we need to ignore the Health state coming from the GameServer heartbeat. This PR enables the use of an environment variable on the NodeAgent to achieve this goal.
=> Ignoring GameServer Health state from heartbeat

cmd/e2e/gameserverapi_test.go
Hotfix to fix a transient error on the gameserver API test routine, we saw it here: https://github.com/PlayFab/thundernetes/runs/7309434067?check_suite_focus=true
=> adding a timeout to a gameserver api test

pkg/operator/controllers/allocation_api_server_test.go, pkg/operator/controllers/controller_utils.go, pkg/operator/controllers/gameserverbuild_controller.go, pkg/operator/controllers/gameserverbuild_controller_test.go, pkg/operator/controllers/test_utils_test.go
When downscaling, the GameServerBuild controller did not distinguish between Initializing and StandingBy GameServers. If a GameServerBuild is upscaling (e.g. waiting for a new Node to join the cluster) and the user starts a downscaling, this can have the impact of StandingBy GameServers being deleted before the Initializing ones. This way, the GameServerBuild will be a little slower to reach the required StandingBy levels.
This PR adds some logic to the GameServerBuild controller to sort the GameServer slice before deletion, so that the Initializing GameServers come before the StandiingBy.
Opportunistically, we refactored the tests on the GameServerBuild controller.
=> fixing deletion ordering

pkg/operator/controllers/allocation_api_server_test.go, pkg/operator/controllers/controller_utils.go
Small fixes for a recent PR #309
=> small fixes

docs/gameserverbuild.md
=> updates to GameServerBuild documentation

docs/architecture.md, docs/gameserverbuild.md
=> more dead links

docs/gsdk/gsdkfooter.md
This PR adds a tag to remove the GSDK footer page from site's navigation.
=> Hiding footer page from navigation

README.md
Modifying main README to highlight the main capabilities and offerings of Thundernetes.
=> modifying main README

cmd/e2e/utilities_test.go
This will help in test errors investigation.
=> adding a method to facilitate better test logging

cmd/e2e/build_crashing_test.go
This PR decreases the sleep time to half a second for the crashing test build e2e test. The previous amount of 2 seconds is unnecessarily large.
=> making crashing build test fail faster

cmd/nodeagent/main.go, cmd/nodeagent/nodeagentmanager.go, cmd/nodeagent/nodeagentmanager_test.go
Fixes #325 
Added parameter to turn off the heartBeatTimeCheckerLoop, so you can run it manually without creating a data race.
=> Fix for data race in heartBeatTimeChecker tests

samples/server-load-simulator/simulator.yaml, samples/standby-forecaster/forecaster.yaml
This PR fixes the image tag for the standby forecaster and the simulator, as reported in #359
=> fixing image tag for intelligent scaling

docs/development/debugging.md, pkg/operator/controllers/controller_utils.go, pkg/operator/controllers/controller_utils_test.go, pkg/operator/controllers/gameserver_controller.go, pkg/operator/controllers/suite_test.go, pkg/operator/main.go
This PR removes the init() method from the operator package, resulting in better code.
=> remove init method from operator package

.github/workflows/e2e.yml, .github/workflows/unit-tests.yml
This PR renames job names on GitHub Actions. Reasoning is that we'd like to make the unit-tests as "required" before merging and it currently has the same name as the e2e tests.
=> rename jobs on GitHub Actions

README.md
#369 changed the GitHub Actions file names so the image on the README failed to load. This PR fixes it
=> fixing README

pkg/operator/api/v1alpha1/gameserver_webhook.go, pkg/operator/api/v1alpha1/gameserver_webhook_test.go, pkg/operator/api/v1alpha1/gameserverbuild_webhook.go, pkg/operator/api/v1alpha1/gameserverbuild_webhook_test.go
This PR does some minor refactoring on the validation webhooks.
=> refactoring webhooks

.github/workflows/unit-tests.yml, pkg/operator/controllers/controller_utils.go, pkg/operator/controllers/gameserverbuild_controller_test.go, pkg/operator/controllers/port_registry.go, pkg/operator/controllers/port_registry_test.go, pkg/operator/controllers/suite_test.go
This PR contains some prep work for #270. Specifically, it refactors portRegistry to be able to return multiple ports per GameServer.
We're gonna need one more PR where we actually remove the finalizer.
=> portregistry returns multiple ports

samples/netcore/Program.cs
This PR adds an optional environmental variable on the .NET Core sample so that the fake game server will terminate after X seconds. This will help in creating a production simulation environment.
=> .NET Core sample - terminate after

samples/netcore/Program.cs, samples/netcore/Startup.cs
This PR makes the netcore sample terminate only after it has transitioned to Active and it also adds some jitter to the timeout.
=> adding some jitter to timeout for netcore sample

cmd/nodeagent/nodeagentmanager.go
Fixes #395 
This PR introduces a check in the NodeAgent delete func where probably the connection with the API server was broken and a `cache.DeletedFinalStateUnknown` object is arriving on the event handler.
=> fixing NodeAgent crash

pkg/operator/controllers/gameserver_controller.go
During a test, we discovered that a lot of errors are generated in the GameServer controller when we try to update the GameServer CR when the Pod has died. This might happen because the GameServer CR has died, so there is no point in updating it. Consequently, we update the error condition to report the error only when the error is not "NotFound".
=> reduce error reporting in GameServer controller

.gitignore, cmd/allocator/build-plugin.sh
Fixed so you didn't have to specify `allocator` twice when using. now `kubectl gameserver` will show the help text and `kubectl gameserver allocate/list` will work as expected. also updated the `~/.bashrc` to more reliably update the `$PATH` variable.
=> Uplugin allocator plugin syntax

pkg/operator/controllers/port_registry_test.go
Sometimes, a PortRegistry unit test that generates two thousand game servers encounters some name collisions and fails, example https://github.com/PlayFab/thundernetes/actions/runs/3098943446
This PR validates that the GameServer names are unique.
=> fixing unit test

cmd/e2e/utilities_test.go
This PR adds some more logging to the e2e tests to assist when the Pod Status is not expected. Hopefully it will help with #345
=> adding PodConditions to e2e

docs/quickstart/sample-minecraft.md, samples/minecraft/README.md, samples/minecraft/sample.yaml
This PR aims to add a documentation to start a Minecraft Java Edition server using Thundernetes. A sample.yaml file was created to be applied to the kubernetes cluster and also there is instructions on how to do so.
=> Minecraft Sample docs

pkg/operator/config/manager/manager.yaml, pkg/operator/controllers/config.go, pkg/operator/controllers/gameserverbuild_controller.go, pkg/operator/controllers/suite_test.go, pkg/operator/main.go
Fixes #157 
Felt like a pretty similar change to #419, so I figured I would take a look. 
- The max number of servers to add/delete are now parameters in gameserverbuild_controller.go
- config.go was created, moving the config struct from main.go to its own file inside controllers
- This allows any controller to now accept the config struct and make use of env variables
- gameserverbuild_controller.go constructor now utilizes the config
- Changing the default values of 20 can be done during deployments via env variables
I did not make these env variables in the makefile. I could refactor the PR to do so if desired, but I figured it would be better to wait on a change fixing the dropped double quotes I faced in #419 . Unlike that one, these wouldn't require an int and string variable so it …
=> Parameterize # of GameServer Creation/Deletion
